/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AcmeFooter {
    }
    interface AcmeForm {
    }
    interface BgForm {
    }
    interface BodyBox {
    }
    interface BodyBox2 {
    }
    interface BodyContainer {
    }
    interface TextBox {
    }
}
declare global {
    interface HTMLAcmeFooterElement extends Components.AcmeFooter, HTMLStencilElement {
    }
    var HTMLAcmeFooterElement: {
        prototype: HTMLAcmeFooterElement;
        new (): HTMLAcmeFooterElement;
    };
    interface HTMLAcmeFormElement extends Components.AcmeForm, HTMLStencilElement {
    }
    var HTMLAcmeFormElement: {
        prototype: HTMLAcmeFormElement;
        new (): HTMLAcmeFormElement;
    };
    interface HTMLBgFormElement extends Components.BgForm, HTMLStencilElement {
    }
    var HTMLBgFormElement: {
        prototype: HTMLBgFormElement;
        new (): HTMLBgFormElement;
    };
    interface HTMLBodyBoxElement extends Components.BodyBox, HTMLStencilElement {
    }
    var HTMLBodyBoxElement: {
        prototype: HTMLBodyBoxElement;
        new (): HTMLBodyBoxElement;
    };
    interface HTMLBodyBox2Element extends Components.BodyBox2, HTMLStencilElement {
    }
    var HTMLBodyBox2Element: {
        prototype: HTMLBodyBox2Element;
        new (): HTMLBodyBox2Element;
    };
    interface HTMLBodyContainerElement extends Components.BodyContainer, HTMLStencilElement {
    }
    var HTMLBodyContainerElement: {
        prototype: HTMLBodyContainerElement;
        new (): HTMLBodyContainerElement;
    };
    interface HTMLTextBoxElement extends Components.TextBox, HTMLStencilElement {
    }
    var HTMLTextBoxElement: {
        prototype: HTMLTextBoxElement;
        new (): HTMLTextBoxElement;
    };
    interface HTMLElementTagNameMap {
        "acme-footer": HTMLAcmeFooterElement;
        "acme-form": HTMLAcmeFormElement;
        "bg-form": HTMLBgFormElement;
        "body-box": HTMLBodyBoxElement;
        "body-box2": HTMLBodyBox2Element;
        "body-container": HTMLBodyContainerElement;
        "text-box": HTMLTextBoxElement;
    }
}
declare namespace LocalJSX {
    interface AcmeFooter {
    }
    interface AcmeForm {
    }
    interface BgForm {
    }
    interface BodyBox {
    }
    interface BodyBox2 {
    }
    interface BodyContainer {
    }
    interface TextBox {
    }
    interface IntrinsicElements {
        "acme-footer": AcmeFooter;
        "acme-form": AcmeForm;
        "bg-form": BgForm;
        "body-box": BodyBox;
        "body-box2": BodyBox2;
        "body-container": BodyContainer;
        "text-box": TextBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "acme-footer": LocalJSX.AcmeFooter & JSXBase.HTMLAttributes<HTMLAcmeFooterElement>;
            "acme-form": LocalJSX.AcmeForm & JSXBase.HTMLAttributes<HTMLAcmeFormElement>;
            "bg-form": LocalJSX.BgForm & JSXBase.HTMLAttributes<HTMLBgFormElement>;
            "body-box": LocalJSX.BodyBox & JSXBase.HTMLAttributes<HTMLBodyBoxElement>;
            "body-box2": LocalJSX.BodyBox2 & JSXBase.HTMLAttributes<HTMLBodyBox2Element>;
            "body-container": LocalJSX.BodyContainer & JSXBase.HTMLAttributes<HTMLBodyContainerElement>;
            "text-box": LocalJSX.TextBox & JSXBase.HTMLAttributes<HTMLTextBoxElement>;
        }
    }
}
